version: "3.5"

services:
    postgres:
        container_name: postgres-article
        image: postgres
        environment:
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_password
            POSTGRES_DB: article
        volumes:
            - ./data:/data/postgres
        ports:
            - "5432:5432"
